# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XyWUcD7zLf1P7dnamSce1hFwrKladqxb
"""

import time

# Bubble Sort Function
def bubble_sort(arr):
    n = len(arr)

    for i in range(n - 1):
        swapped = False

        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                # Swap elements
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True

        if not swapped:
            break

# User Input
arr = list(map(int, input("Enter numbers separated by spaces: ").split()))

# Start Time
start_time = time.perf_counter()

# Sort the array
bubble_sort(arr)

# End Time
end_time = time.perf_counter()

# Display Results
print("\nSorted Array:", arr)
print("Execution Time: {:.8f} seconds".format(end_time - start_time))

# Display Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(n)")
print("Average Case : O(n^2)")
print("Worst Case   : O(n^2)")
print("Space Complexity: O(1)")

import time

# Selection Sort Function
def selection_sort(arr):
    n = len(arr)

    for i in range(n - 1):
        # Assume the first element is the minimum
        min_index = i

        # Find the smallest element in the remaining array
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        # Swap the found minimum element with the first element
        arr[i], arr[min_index] = arr[min_index], arr[i]


# User Input
arr = list(map(int, input("Enter numbers separated by spaces: ").split()))

# Start execution time
start_time = time.perf_counter()

# Apply Selection Sort
selection_sort(arr)

# End execution time
end_time = time.perf_counter()

# Display output
print("\nSorted Array:", arr)
print("Execution Time: {:.8f} seconds".format(end_time - start_time))

# Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(n²)")
print("Average Case : O(n²)")
print("Worst Case   : O(n²)")
print("Space Complexity: O(1)")

import time

# Insertion Sort Function
def insertion_sort(arr):
    n = len(arr)

    for i in range(1, n):
        key = arr[i]
        j = i - 1

        # Move elements greater than key one position ahead
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j = j - 1

        # Insert key at the correct position
        arr[j + 1] = key


# User Input
arr = list(map(int, input("Enter numbers separated by spaces: ").split()))

# Start execution time
start_time = time.perf_counter()

# Apply Insertion Sort
insertion_sort(arr)

# End execution time
end_time = time.perf_counter()

# Display output
print("\nSorted Array:", arr)
print("Execution Time: {:.8f} seconds".format(end_time - start_time))

# Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(n)")
print("Average Case : O(n²)")
print("Worst Case   : O(n²)")
print("Space Complexity: O(1)")

import time

# Merge Sort Function
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2

        # Divide the array into two halves
        left = arr[:mid]
        right = arr[mid:]

        # Recursively sort both halves
        merge_sort(left)
        merge_sort(right)

        # Merge the sorted halves
        i = j = k = 0

        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                arr[k] = left[i]
                i += 1
            else:
                arr[k] = right[j]
                j += 1
            k += 1

        # Copy remaining elements of left half
        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1

        # Copy remaining elements of right half
        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1


# User Input
arr = list(map(int, input("Enter numbers separated by spaces: ").split()))

# Start execution time
start_time = time.perf_counter()

# Apply Merge Sort
merge_sort(arr)

# End execution time
end_time = time.perf_counter()

# Display output
print("\nSorted Array:", arr)
print("Execution Time: {:.8f} seconds".format(end_time - start_time))

# Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")
print("Space Complexity: O(n)")

import time

# Quick Sort Function
def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    # Select pivot element
    pivot = arr[len(arr) // 2]

    # Divide array into three parts
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    # Recursively sort left and right parts
    return quick_sort(left) + middle + quick_sort(right)


# User Input
arr = list(map(int, input("Enter numbers separated by spaces: ").split()))

# Start execution time
start_time = time.perf_counter()

# Apply Quick Sort
sorted_array = quick_sort(arr)

# End execution time
end_time = time.perf_counter()

# Display output
print("\nSorted Array:", sorted_array)
print("Execution Time: {:.8f} seconds".format(end_time - start_time))

# Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n²)")
print("Space Complexity: O(n)")
